"""Adiciona a tabela de Presentes

Revision ID: 59d66830bbd7 
Revises: {ID_DA_VERSAO_ANTERIOR}
Create Date: {DATA_DA_CRIAÇAO}

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '59d66830bbd7' # O seu pode ser diferente
down_revision = '{ID_DA_VERSAO_ANTERIOR}' # O seu pode ser diferente
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presente',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome_item', sa.String(length=200), nullable=False),
        sa.Column('ganho', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('convidado_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['convidado_id'], ['convidado.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # A MUDANÇA ESTÁ AQUI, DENTRO DO 'batch_alter_table'
    with op.batch_alter_table('convidado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmado', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convidado', schema=None) as batch_op:
        batch_op.drop_column('confirmado')

    op.drop_table('presente')
    # ### end Alembic commands ###